FROM node:22.15-alpine AS builder

WORKDIR /app

COPY frontend/package*.json ./
RUN npm i
#RUN npm ci

COPY frontend/ .
RUN npm run build


FROM nginx:alpine AS runner

COPY --from=builder /app/dist /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx","-g", "daemon off;"]