version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

#  prod:
#    build:
#      context: .
#      dockerfile: Dockerfile.prod
#    ports:
#      - "8080:80"