version: '3.8'

services:

  frontend:

    build:

      context: .

      dockerfile: Dockerfile

    ports:

      - "5173:5173"

    volumes:

      - ./frontend:/app

      - /app/node_modules

    stdin_open: true

    tty: true