name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: 22.15

      - name: Instalar dependências
        run: npm i

      - name: Rodar os testes
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success()

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Login no Docker Hub (opcional)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Testar login no Docker
        run: docker info

      - name: Build da imagem de produção
        run: docker build -f Dockerfile.prod -t frontend:latest .

      # Para enviar para o Docker Hub
      #- name: Push imagem para o Docker Hub
      #  run: docker tag frontend:latest meu-usuario/frontend:latest && docker push meu-usuario/frontend:latest

      - name: Deploy para Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}